### ISSUE TITLE
CodeAction: expected 0 arguments

### ISSUE THREAD

**Issue by eruizc-dev** [RishabhRD/nvim-lsputils#29]
### Issue
Been doing some Java and when invoking for CodeActions I get the following error and no popup appears:

```
Error executing vim.schedule lua callback: ...ig/nvim/plugged/nvim-lsputils/lua/lsputil/codeAction.lua:86: Expected 0 arguments
```

Code actions do work in other situations. What characterizes that specific one is that when I removed lsp-utils I saw 50 code actions in total that are presented by default with `less`. It may be a limitation of the current implementation that doesn't allow more than a certain amount of results. If you wanna simulate this many code actions, use JDTLS. Call for `List<T>` and run code actions to import the library.

```
List<Integer> numbers;
```

![image](https://user-images.githubusercontent.com/58179604/119693714-eed47a80-be22-11eb-89aa-12fc868c32b5.png)

### Expected result:

Code actions popup to appear

### Configuration

 1. JDTLS installed with [jdtls-launcher](https://github.com/eruizc-dev/jdtls-launcher)
 2. LSP config: `require("lspconfig").jdtls.setup{ cmd = { "jdtls" } }`
 3. Code actions config: `vim.lsp.handlers['textDocument/codeAction'] = require'lsputil.codeAction'.code_action_handler`

 -

**Comment by RishabhRD** [comment]
#28 PR should solve the issue. However, nvim-lsputils makes no changes to truncate the number of code-actions from the language server. Here is what it looks like on my machine:
![lists_png](https://user-images.githubusercontent.com/26287448/119703329-10aa1d80-be74-11eb-8bd4-e16146189c5a.png)

nvim-lsputils just displays it in good fashion and add some keybinds to each entry of popup.

**Comment by eruizc-dev** [comment]
@RishabhRD I updated and tried again and as you mentioned, the error doesn't appear anymore.
I now get the error `Not enough space to draw popup`, which is better but still troublesome since I get no code actions at all
Would you consider truncating or calling the default code action method in that case as a quickfix? With the proper implementation being a scrollable popup
I may be able to help, don't have much to do in the week

**Comment by RishabhRD** [comment]
Yes, I see. If code-action doesn't fit the screen the popup size should decrease. There is a bug there. I tried to fix it codeaction_height branch: [codeaction_height](https://github.com/RishabhRD/nvim-lsputils/tree/codeaction_height). Can you confirm for me if it works?

This branch should fix the issue for now, but I am considering a major rewrite to make the plugin more modular and extensible. I am planning to utilize popup.nvim in popfix to make popups robust instead of writing it myself. And it is almost sure that popup.nvim is going to be merged in upstream in few days so I am really considering this. I would make PR regarding this in popfix and nvim-lsputils. If you are willing to help, I would tag you.

**Comment by eruizc-dev** [comment]
You really work fast, displays 112 results without a problem! 

![image](https://user-images.githubusercontent.com/58179604/119729898-8c43a480-be4b-11eb-9488-38a587cfbc47.png)

Regarding popup.nvim, sure! Ping me whenever you need a hand. Can't promise much since I'm a newbie but sure will take a look at it and throw some code

**Comment by RishabhRD** [comment]
Sure! I have merged the branch to master so closing the issue. Thanks for reporting.
