### ISSUE TITLE
Using <C-c> to close popup menus/buffers

### ISSUE THREAD

**Issue by ludwj61** [RishabhRD/nvim-lsputils#9]
Quick question: would it be possible to use ``control + c`` to exit popups like ``escape`` is being used now?

Thanks for the plugin and your tutorials.

**Comment by RishabhRD** [comment]
Thank for feedback!

yes! it is possible using lua api. For custom keybinds you can use:
`require'lsputil.locations'.key_maps['n']['<C-c>'] = require'popfix.action'.close_cancelled`
(use close_selected insted of close_cancelled if you want current option to be chosen and then closed.)
For similar effect in document_symbols and workspace_symbols window use lsputil.symbols instead of lsputil.locations

String can also be mapped. You can refer last section of readme to get an idea about that. 

Hope it solves your problem. :-)

**Comment by ludwj61** [comment]
Thanks!
